/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const VlogCategory = IDL.Variant({
  'vlog' : IDL.Null,
  'trading' : IDL.Null,
  'promo' : IDL.Null,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'createdAt' : IDL.Int,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const VlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnailUrl' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'category' : VlogCategory,
  'videoUrl' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createVlogPost' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, VlogCategory],
      [],
      [],
    ),
  'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteVlogPost' : IDL.Func([IDL.Nat], [], []),
  'fetchCryptoPrices' : IDL.Func([], [IDL.Text], []),
  'fetchWorldNews' : IDL.Func([], [IDL.Text], []),
  'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
  'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVlogPost' : IDL.Func([IDL.Nat], [VlogPost], ['query']),
  'getVlogPosts' : IDL.Func([], [IDL.Vec(VlogPost)], ['query']),
  'getVlogPostsByCategory' : IDL.Func(
      [VlogCategory],
      [IDL.Vec(VlogPost)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAnnouncement' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'updateVlogPost' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, VlogCategory],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const VlogCategory = IDL.Variant({
    'vlog' : IDL.Null,
    'trading' : IDL.Null,
    'promo' : IDL.Null,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'createdAt' : IDL.Int,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const VlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnailUrl' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'category' : VlogCategory,
    'videoUrl' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createVlogPost' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, VlogCategory],
        [],
        [],
      ),
    'deleteAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteVlogPost' : IDL.Func([IDL.Nat], [], []),
    'fetchCryptoPrices' : IDL.Func([], [IDL.Text], []),
    'fetchWorldNews' : IDL.Func([], [IDL.Text], []),
    'getAnnouncement' : IDL.Func([IDL.Nat], [Announcement], ['query']),
    'getAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVlogPost' : IDL.Func([IDL.Nat], [VlogPost], ['query']),
    'getVlogPosts' : IDL.Func([], [IDL.Vec(VlogPost)], ['query']),
    'getVlogPostsByCategory' : IDL.Func(
        [VlogCategory],
        [IDL.Vec(VlogPost)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAnnouncement' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'updateVlogPost' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text, VlogCategory],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };