/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Announcement {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'createdAt' : bigint,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type VlogCategory = { 'vlog' : null } |
  { 'trading' : null } |
  { 'promo' : null };
export interface VlogPost {
  'id' : bigint,
  'title' : string,
  'thumbnailUrl' : string,
  'createdAt' : bigint,
  'description' : string,
  'category' : VlogCategory,
  'videoUrl' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAnnouncement' : ActorMethod<[string, string], undefined>,
  'createVlogPost' : ActorMethod<
    [string, string, string, string, VlogCategory],
    undefined
  >,
  'deleteAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteVlogPost' : ActorMethod<[bigint], undefined>,
  'fetchCryptoPrices' : ActorMethod<[], string>,
  'fetchWorldNews' : ActorMethod<[], string>,
  'getAnnouncement' : ActorMethod<[bigint], Announcement>,
  'getAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVlogPost' : ActorMethod<[bigint], VlogPost>,
  'getVlogPosts' : ActorMethod<[], Array<VlogPost>>,
  'getVlogPostsByCategory' : ActorMethod<[VlogCategory], Array<VlogPost>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAnnouncement' : ActorMethod<[bigint, string, string], undefined>,
  'updateVlogPost' : ActorMethod<
    [bigint, string, string, string, string, VlogCategory],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];